---

- name: Unzip Pleroma release
  become: true
  become_user: "{{ pleroma_user }}"
  ansible.builtin.unarchive:
    src: "https://git.pleroma.social/api/v4/projects/2/jobs/artifacts/stable/download?job={{ lookup('pipe', 'dpkg --print-architecture') }}"
    dest: "/tmp/"
    remote_src: true

- name: Ensure correct path and permissions of files
  become: true
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items:
    - rm /opt/pleroma/* -r || true
    - mv /tmp/release/* {{ pleroma_base_path }}/
    - rm /tmp/release -rf

- name: Run pleroma setup
  become: true
  become_user: "{{ pleroma_user }}"
  ansible.builtin.shell: 
    cmd: "{ {% for response in pleroma_setup_responses %} echo \"{{ response }}\"; {% endfor %} } | ./bin/pleroma_ctl instance gen --force --output /etc/pleroma/config.exs --output-psql /tmp/setup_db.psql"
  args:
    chdir: "{{ pleroma_base_path }}"
  register: setup_log

- name: Disable captcha
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pleroma/config.exs
    block: |
      config :pleroma, Pleroma.Captcha,
        enabled: false

