---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-flask
      - python3-click
      - python3-mastodon
      - gunicorn

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pleroma_user }}"
    group: "{{ pleroma_user }}"
  with_items:
    - /opt/mastobot/
    - /opt/mastobot/media/
    - /opt/mastobot/secrets/

- name: Deploy media
  become: true
  ansible.builtin.copy:
    src: "{{ pleroma_media_src }}/"
    dest: /opt/mastobot/media/
    owner: "{{ pleroma_user }}"
    group: "{{ pleroma_user }}"
    mode: "0755"
  when: pleroma_media_src is defined

- name: Deploy mastobot server
  become: true
  ansible.builtin.copy:
    src: files/mastobot.py
    dest: /opt/mastobot/mastobot.py
    owner: "{{ pleroma_user }}"
    group: "{{ pleroma_user }}"
    mode: "0755"

- name: Copy mastobot config
  become: true
  ansible.builtin.template:
    src: templates/mastobot_config.yaml.j2
    dest: /opt/mastobot/config.yaml
    owner: "{{ pleroma_user }}"
    group: "{{ pleroma_user }}"

- name: Copying service-template to server
  become: true
  ansible.builtin.template:
    src: templates/mastobot.service.j2
    dest: /etc/systemd/system/mastobot.service
    mode: preserve

- name: Start service mastobot
  become: true
  ansible.builtin.systemd:
    name: mastobot.service
    state: restarted
    daemon_reload: true
    enabled: true

- name: Start service pleroma
  become: true
  ansible.builtin.systemd:
    name: pleroma
    state: restarted

- name: Wait 30 seconds for pleroma
  ansible.builtin.wait_for:
    timeout: 30

- name: Run Mastobot Bootstrap
  become: true
  ansible.builtin.command:
    cmd: /opt/mastobot/mastobot.py init

- name: Turn on autopopulate
  ansible.builtin.uri:
    url: https://127.0.0.1:5000/start_population
    method: POST
    validate_certs: false
  register: post_answer
  when: pleroma_autopopulate

- ansible.builtin.debug:
    msg: "{{ post_answer.json }}"
  when: post_answer is defined
