---

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name: 
      - python3-mastodon
      - python3-click

- name: Create config directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/mastodon/media/
    - /etc/mastobot

- name: Create mastobot config
  become: true
  ansible.builtin.copy:
    dest: /etc/mastobot/config.yaml
    mode: 0644
    content: |
      server_name: {{ pleroma_domain_name }}
      deploy_path: {{ pleroma_base_path }}

- name: Create mastobot Bootsrap config
  become: true
  ansible.builtin.copy:
    dest: /etc/mastobot/bootstrap.yaml
    mode: 0644
    content: |
      admin_user: {{ pleroma_admin_user }}
      admin_password: {{ pleroma_admin_password }}
      mastodon_users: {{ pleroma_users }}

- name: Deploy bootstrap media
  become: true
  ansible.builtin.copy:
    src: files/bootstrap_media/
    dest: "/opt/mastodon/media/"
    mode: 0755

- name: Create masto_bot directory
  become: true
  ansible.builtin.file:
    path: "{{ pleroma_base_path }}/masto_bot"
    state: directory
    owner: "{{ pleroma_user }}"
    group: "{{ pleroma_user }}"

- name: Deploy mastobot
  become: true
  ansible.builtin.copy:
    dest: "{{ pleroma_base_path }}/masto_bot.py"
    src: masto_bot.py
    mode: 0755

- name: Deploy mastobot bootstrap
  tags: ["mastobot"]
  become: true
  ansible.builtin.copy:
    dest: "{{ pleroma_base_path }}/masto_bot_bootstrap.py"
    src: masto_bot_bootstrap.py
    mode: 0755

- name: Create mastobot startscript
  become: true
  ansible.builtin.copy:
    dest: "/usr/bin/mastobot"
    mode: 0755
    content: |
      #!/bin/bash
      {{ pleroma_base_path }}/masto_bot.py "$@"

- name: Run Mastobot Bootstrap
  become: true
  ansible.builtin.shell:
    cmd: "{{ pleroma_base_path }}/masto_bot_bootstrap.py"
    chdir: "{{ pleroma_base_path }}"

